name: "TrafficBot Pro"
description: "Multi-city automated traffic alerts to Microsoft Teams using GitHub Actions."
author: "Ramesh0708"
branding:
  icon: traffic-light
  color: red

inputs:
  city:
    description: "City to fetch traffic updates for (e.g., Pune, Mumbai, Bangalore)"
    required: false
    default: "Pune"

  teams_webhook_url:
    description: "Microsoft Teams Incoming Webhook URL"
    required: true

  enable_creator_spotlight:
    description: "Promote your YouTube channel (yes/no)"
    required: false
    default: "no"

  youtube_link:
    description: "Link to your YouTube channel"
    required: false
    default: "https://youtube.com/@rawbyshivam"

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash

    - name: Run TrafficBot Pro
      run: |
        CITY="${{ inputs.city }}" \
        TEAMS_WEBHOOK_URL="${{ inputs.teams_webhook_url }}" \
        CREATOR_SPOTLIGHT="${{ inputs.enable_creator_spotlight }}" \
        YOUTUBE_LINK="${{ inputs.youtube_link }}" \
        python $GITHUB_ACTION_PATH/trafficbot_pro.py
      shell: bash
